echo("HELLO WORLD")
echo("My name is Aarsh and I made Py2Shell")
echo("This Py2Shell script is supposed to do some tasks.")
echo("Task 1 - Fastfetch")
fastfetch()
echo("Task 2 - Launch Kate and Konsole")
kate()
konsole()
echo("Task 3 - Install GCC using Pacman")
pacman("-Syu","gcc")
echo("Task 4 - Get Environmental Variables")
env()
echo("If the output shell script did all these tasks successfully, then Py2Shell transpiled the script flawlessly.")
